# Generated by Django 4.2.8 on 2023-12-14 17:37

from django.db import migrations, models
import uuid


def gen_uuid(apps, schema_editor):
    model = apps.get_model("ims", "Link")
    for row in model.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
