# Generated by Django 4.2.8 on 2023-12-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0003_alter_link_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='verified_at',
            field=models.DateTimeField(null=True),
        ),
    ]
