# Generated by Django 4.2.8 on 2023-12-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0004_alter_link_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='member_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='link',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
