# Generated by Django 5.0 on 2023-12-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0006_alter_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(default='Update...', max_length=128),
        ),
    ]
