# Generated by Django 5.0 on 2023-12-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0007_alter_link_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.CharField(max_length=512, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='link',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='是否有效'),
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(default='Update...', max_length=128, verbose_name='Name'),
        ),
    ]
