# Generated by Django 5.0 on 2023-12-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0011_auto_20231229_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='category',
            field=models.CharField(choices=[('unknown', '未知'), ('group', '群组'), ('channel', '频道'), ('personal', '个人')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='link',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='link',
            name='member_count',
            field=models.IntegerField(default=0, verbose_name='用户数'),
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(default='Updating...', max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='link',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='验证时间'),
        ),
    ]
