# Generated by Django 5.0.4 on 2024-04-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0014_link_verified_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='search_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
