# Generated by Django 5.0.4 on 2024-10-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0015_alter_search_search_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('click_count', models.IntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_at', models.DateTimeField(auto_now=True)),
                ('end_at', models.DateTimeField()),
            ],
        ),
    ]
