# Generated by Django 5.0.9 on 2024-10-07 15:11

from django.db import migrations, models

def add_initial_places(apps, schema_editor):
    Place = apps.get_model('ims', 'AdPlace')
    Place.objects.create(code=1, name='首页')
    Place.objects.create(code=2, name='详情页')

class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0017_ad_image_ad_place_ad_url_alter_ad_start_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SmallIntegerField(db_index=True, unique=True, verbose_name='位置代码')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.RemoveField(
            model_name='ad',
            name='place',
        ),
        migrations.AddField(
            model_name='ad',
            name='place',
            field=models.ManyToManyField(to='ims.adplace', verbose_name='展示位置'),
        ),

        migrations.RunPython(add_initial_places),
    ]
