# Generated by Django 5.0.9 on 2024-10-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0018_adplace_alter_ad_image_remove_ad_place_ad_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='status',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
    ]
