# Generated by Django 5.0.9 on 2024-10-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0019_ad_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.TextField(max_length=512, verbose_name='Description'),
        ),
    ]
