# docker-compose-prod.yml
version: '3'

services:
  web:
    container_name: imindex-web-1
    build: .
    command: /bin/bash -c "python manage.py compilemessages && python manage.py collectstatic --noinput && _for_deploy/wait-for-db.sh db && python manage.py migrate && python manage.py imindex_install && gunicorn mysite.wsgi:application --bind 0.0.0.0:8000"
    restart: always
#    volumes:
#      - .:/code
    ports:
      - "8000:8000"
#      - "80:8000"
    environment:
      SECRET_KEY: kNU9dV9SQYZyy1F3pSKw1KyvdeNuer07
      DJANGO_DEBUG: False
      DB_NAME: pgdb
      DB_USER: pgdb
      DB_PASSWORD: pgpass
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $$!; done;'
    depends_on:
      - nginx

  celery:
    container_name: imindex-celery-1
    build: .
    command: celery -A mysite worker --loglevel=info
    volumes:
      - .:/code
    environment:
      SECRET_KEY: kNU9dV9SQYZyy1F3pSKw1KyvdeNuer07
      DB_NAME: pgdb
      DB_USER: pgdb
      DB_PASSWORD: pgpass
    depends_on:
      - db
      - redis

  cron:
    build: .
    volumes:
      - .:/code
      - ./_for_deploy/django_cron_job:/etc/cron.d/django_cron_job
    command: cron -f

  db:
    container_name: imindex-db-1
    image: postgres
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pgdb
      POSTGRES_USER: pgdb
      POSTGRES_PASSWORD: pgpass
    ports:
      - "5432:5432"

  redis:
    container_name: imindex-redis-1
    image: redis
    restart: always
    volumes:
      - ./redisdata:/data
    ports:
      - "6379:6379"

volumes:
  certbot-conf:
  certbot-www:
