version: '3'

services:
  certbot:
    image: certbot/certbot
    container_name: certbot-apply-for-ssl
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./letsencrypt/:/etc/letsencrypt/
    ports:
      - "80:80"
    command: certonly --standalone -d tnav.me --agree-tos --non-interactive
