version: '3'

services:
  web:
    container_name: imindex-web-1
    build: .
    command: /bin/bash -c "python manage.py compilemessages && python manage.py collectstatic --noinput && _for_deploy/wait-for-db.sh db && service cron start && python manage.py migrate && python manage.py imindex_install && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: kNU9dV9SQYZyy1F3pSKw1KyvdeNuer07
      DJANGO_DEBUG: True
      DB_NAME: pgdb
      DB_USER: pgdb
      DB_PASSWORD: pgpass
    depends_on:
      - db
      - redis

  celery:
    container_name: imindex-celery-1
    build: .
    command: celery -A mysite worker --loglevel=info
    volumes:
      - .:/code
    environment:
      SECRET_KEY: kNU9dV9SQYZyy1F3pSKw1KyvdeNuer07
      DB_NAME: pgdb
      DB_USER: pgdb
      DB_PASSWORD: pgpass
    depends_on:
      - db
      - redis

  db:
    container_name: imindex-db-1
    image: postgres
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pgdb
      POSTGRES_USER: pgdb
      POSTGRES_PASSWORD: pgpass
    ports:
      - "5432:5432"

  redis:
    container_name: imindex-redis-1
    image: redis
    restart: always
    volumes:
      - ./redisdata:/data
    ports:
      - "6379:6379"
