# docker-compose-prod.yml
version: '3'

services:
  web:
    container_name: imindex-web-1
    build: .
    command: /bin/bash -c "./wait-for-db.sh db && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py install && gunicorn mysite.wsgi:application --bind 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: kNU9dV9SQYZyy1F3pSKw1KyvdeNuer07
      DJANGO_DEBUG: False
      DB_NAME: pgdb
      DB_USER: pgdb
      DB_PASSWORD: pgpass
    depends_on:
      - db
      - redis

#  celery:
#      build: .
#      command: celery -A mysite worker --loglevel=info
#      volumes:
#        - .:/code
#      environment:
#        SECRET_KEY: kNU9dV9SQYZyy1F3pSKw1KyvdeNuer07
#        DB_NAME: pgdb
#        DB_USER: pgdb
#        DB_PASSWORD: pgpass

  cron:
    build: .
    volumes:
      - .:/code
      - ./django_cron_job:/etc/cron.d/django_cron_job
    command: cron -f

  db:
    container_name: imindex-db-1
    image: postgres
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pgdb
      POSTGRES_USER: pgdb
      POSTGRES_PASSWORD: pgpass

  redis:
    container_name: imindex-redis-1
    image: redis
    restart: always
    ports:
      - "6379:6379"
