version: '3'

services:
  web:
    container_name: imindex-web-1
    build: .
    command: /bin/bash -c "./wait-for-db.sh db && python manage.py migrate && gunicorn mysite.wsgi:application --bind 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: kNU9dV9SQYZyy1F3pSKw1KyvdeNuer07
      DJANGO_DEBUG: False
      DB_NAME: pgdb
      DB_USER: pgdb
      DB_PASSWORD: pgpass
    depends_on:
      - db
      - redis

  db:
    container_name: imindex-db-1
    image: postgres
    environment:
      POSTGRES_DB: pgdb
      POSTGRES_USER: pgdb
      POSTGRES_PASSWORD: pgpass

  redis:
    container_name: imindex-redis-1
    image: redis
    restart: always
    ports:
      - "6379:6379"
