version: '3'
services:
  web:
    image: dba18714/imindex:latest
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: kNU9dV9SQYZyy1F3pSKw1KyvdeNuer07
      DJANGO_DEBUG: False
      DB_NAME: pgdb
      DB_USER: pgdb
      DB_PASSWORD: pgpass
    # 更多生产环境配置
  db:
    image: postgres
    environment:
      POSTGRES_DB: pgdb
      POSTGRES_USER: pgdb
      POSTGRES_PASSWORD: pgpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
volumes:
  postgres_data:
