# docker-compose-dev.yml
version: '3'

services:
  web:
    container_name: imindex-web-1
    build: .
    command: /bin/bash -c "chmod +x _for_deploy/start.sh && _for_deploy/start.sh"
    restart: always
    volumes:
      - ./common:/code/common
      - ./data/upload_file:/code/data/upload_file
      - ./crawler:/code/crawler
      - ./tmp.py:/code/tmp.py
      - ./ims:/code/ims
      - ./mysite:/code/mysite
      - ./templates:/code/templates
      - ./static:/code/static
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: kNU9dV9SQYZyy1F3pSKw1KyvdeNuer07
      DJANGO_DEBUG: True
      DB_NAME: pgdb
      DB_USER: pgdb
      DB_PASSWORD: pgpass
    depends_on:
      - db
      - redis

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://:RDFGDxpI1h@redis:6379/1
      - FLOWER_BASIC_AUTH=${FLOWER_BASIC_AUTH}
    command: ["celery", "flower", "--broker=redis://:RDFGDxpI1h@redis:6379/1", "--basic_auth=${FLOWER_BASIC_AUTH}"]
    ports:
      - "5555:5555"

  celery:
    container_name: imindex-celery-1
    build: .
    command: celery -A mysite worker --loglevel=info
    volumes:
      - .:/code
    environment:
      SECRET_KEY: kNU9dV9SQYZyy1F3pSKw1KyvdeNuer07
      DB_NAME: pgdb
      DB_USER: pgdb
      DB_PASSWORD: pgpass
    depends_on:
      - db
      - redis

  db:
    container_name: imindex-db-1
    image: postgres
    restart: always
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pgdb
      POSTGRES_USER: pgdb
      POSTGRES_PASSWORD: pgpass
    ports:
      - "5432:5432"

  redis:
    container_name: imindex-redis-1
    image: redis
    restart: always
    volumes:
      - redisdata:/data
      - ./_for_deploy/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf

volumes:
  redisdata:
