FROM python:3.11.4
ENV PYTHONUNBUFFERED 1
ENV DJANGO_ENV=production
RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . /code/
RUN python manage.py collectstatic --noinput
RUN python manage.py migrate --noinput
RUN python manage.py install

COPY start.sh /code/
RUN chmod +x /code/start.sh

CMD ["/code/start.sh"]
