# fly.toml app configuration file generated for imindex on 2023-12-13T18:41:00+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "imindex"
primary_region = "nrt"
console_command = "/code/manage.py shell"

[build]

[deploy]
  release_command = "python manage.py migrate --noinput"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

#[[statics]]
#  guest_path = "/code/static-build"
#  url_prefix = "/static-build/"

# 添加的自动缩放配置
[experimental]
  auto_scaling = true # 启用自动缩放

  [[services]]
    internal_port = 8000
    processes = ["app"]

    # 缩放设置
    [services.concurrency]
      hard_limit = 25 # 设置每个实例的并发请求硬限制
      soft_limit = 20 # 设置并发请求的软限制
      type = "requests" # 设置限制类型为请求

    # 自动缩放参数
    [services.scaling]
      min = 1   # 最小实例数
      max = 2  # 最大实例数
      # 以下是触发自动缩放的指标
      [services.scaling.targets]
        cpu = 95  # CPU 使用率百分比
        memory = 900  # 内存使用量（MB）