name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            set -e
            
            directory_path="/app/imindex"
            
            echo "创建目录 $directory_path（如果不存在）"
            mkdir -p $directory_path
            
            echo "检查并安装 Git"
            if ! command -v git &> /dev/null; then
              sudo apt-get update
              sudo apt-get install -y git
            fi
            
            cd $directory_path 
            
            if [ -z "$(ls -A $directory_path)" ]; then
              echo "目录为空，Clone git"
              git clone https://github.com/dba18714/imindex.git .
            else
              echo "目录不为空 Pull git"
              git reset --hard origin/main && git pull origin main
            fi

            echo "检查并安装 Curl"
            if ! command -v curl &> /dev/null; then
              sudo DEBIAN_FRONTEND=noninteractive apt-get update
              sudo DEBIAN_FRONTEND=noninteractive apt-get install -y curl
            fi
  
            echo "检查并安装 Docker"
            if ! command -v docker &>/dev/null; then
              echo "Installing Docker..."
              sudo DEBIAN_FRONTEND=noninteractive apt-get update
              sudo DEBIAN_FRONTEND=noninteractive apt-get install -y docker.io
            fi
            
            echo "检查并安装 Docker Compose"
            if ! command -v docker-compose &> /dev/null; then
              sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi 
            
            echo "检查并安装 Node.js 和 npm"
            if ! command -v node &> /dev/null || ! command -v npm &> /dev/null; then
              echo "Installing Node.js and npm..."
              curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
            
            if [ ! -d "$directory_path/letsencrypt/live" ]; then
              # docker-compose -f docker-compose-prod.yml down --remove-orphans
              docker-compose -f docker-compose-prod-apply-for-ssl.yml down --remove-orphans
            
              echo "$directory_path/letsencrypt/live 目录不存在，将执行自动获取SSL证书"
              docker-compose -f docker-compose-prod-apply-for-ssl.yml up -d --build --remove-orphans
            
              # echo "等待 10 秒"
              # sleep 121
              # exit

              echo "正在关闭 docker-compose-prod-apply-for-ssl.yml"
              docker-compose -f docker-compose-prod-apply-for-ssl.yml down --remove-orphans
            
            fi
            
            cd jstoolchain
            echo "安装 npm 依赖"
            npm install
            echo "npm run tailwind-build"
            npm run tailwind-build
            cd ..
            
            docker-compose -f docker-compose-prod.yml down --remove-orphans
            docker-compose -f docker-compose-prod.yml up -d --build --remove-orphans
