name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: dba18714/imindex:latest

      - name: Print GITHUB_WORKSPACE
        run: echo $GITHUB_WORKSPACE # 这里能访问到$GITHUB_WORKSPACE

      - name: List files in current directory
        run: ls -la

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            WORKDIR=${{ github.workspace }}
            echo "工作目录: $WORKDIR"
            cd $WORKDIR
            
            echo "检查并安装 Docker"
            if ! command -v docker &>/dev/null; then
                echo "Installing Docker..."
                sudo apt-get update
                sudo apt-get install -y docker.io
            fi
            
            echo "拉取 Docker 镜像"
            docker pull dba18714/imindex:latest     
            
            echo "打印当前工作目录："
            pwd
            echo "列出当前目录内容："
            ls -la
            
            echo "执行 Docker Compose："
            if ! command -v curl &>/dev/null; then
                echo "Installing Curl..."
                sudo apt-get update
                sudo apt-get install -y curl
            fi
            if ! command -v docker-compose &>/dev/null; then
                echo "Installing Docker Compose..."
                sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                sudo chmod +x /usr/local/bin/docker-compose
            fi
            docker-compose up -d