name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            directory_path="/app/imindex"
            
            echo "创建目录 $directory_path（如果不存在）"
            mkdir -p $directory_path
            
            echo "检查并安装 Git"
            if ! command -v git &> /dev/null; then
              sudo apt-get update
              sudo apt-get install -y git
            fi
            
            cd /app/imindex
            
            if [ -z "$(ls -A $directory_path)" ]; then
              echo "目录为空，Clone git"
              git clone https://github.com/dba18714/imindex.git .
            else
              echo "目录不为空 Pull git"
              git pull
            fi

            echo "检查并安装 Curl"
            if ! command -v curl &> /dev/null; then
              sudo DEBIAN_FRONTEND=noninteractive apt-get update
              sudo DEBIAN_FRONTEND=noninteractive apt-get install -y curl
            fi
  
            echo "检查并安装 Docker"
            if ! command -v docker &>/dev/null; then
              echo "Installing Docker..."
              sudo DEBIAN_FRONTEND=noninteractive apt-get update
              sudo DEBIAN_FRONTEND=noninteractive apt-get install -y docker.io
            fi
            
            echo "检查并安装 Docker Compose"
            if ! command -v docker-compose &> /dev/null; then
              sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi
            
            docker-compose -f docker-compose-prod.yml down
            docker-compose -f docker-compose-prod.yml up -d
