name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Archive of Repository
        run: tar -czf repo.tar.gz --exclude='.git/*' --exclude='node_modules/*' .

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "创建目录 /app/imindex（如果不存在）"
            mkdir -p /app/imindex

            echo "传输归档文件到服务器"
            rsync -avz repo.tar.gz /app/imindex/

            echo "在服务器上解压归档"
            cd /app/imindex
            tar -xzf repo.tar.gz
            rm repo.tar.gz

            echo "检查并安装 Rsync"
            if ! command -v rsync &> /dev/null; then
              sudo DEBIAN_FRONTEND=noninteractive apt-get update
              sudo DEBIAN_FRONTEND=noninteractive apt-get install -y rsync
            fi

            echo "检查并安装 Curl"
            if ! command -v curl &> /dev/null; then
              sudo DEBIAN_FRONTEND=noninteractive apt-get update
              sudo DEBIAN_FRONTEND=noninteractive apt-get install -y curl
            fi
  
            echo "检查并安装 Docker"
            if ! command -v docker &>/dev/null; then
              echo "Installing Docker..."
              sudo DEBIAN_FRONTEND=noninteractive apt-get update
              sudo DEBIAN_FRONTEND=noninteractive apt-get install -y docker.io
            fi
            
            echo "检查并安装 Docker Compose"
            if ! command -v docker-compose &> /dev/null; then
              sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            cd /app/imindex
            
            docker-compose -f docker-compose-prod.yml down
            docker-compose -f docker-compose-prod.yml up -d
